name: papilio_note
description: Markdown notes anywhere

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.10+2
  navigation_drawer_menu: ^1.0.0-beta
  papilio:
    path: ../../../papilio
  path_provider: ^2.0.11
  sliding_up_panel: ^2.0.0+1
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.11
  dart_code_metrics: ^4.16.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mockito: ^5.2.0

flutter:
  uses-material-design: true

fonts:
  - family: Raleway
    fonts:
      - asset: assets/fonts/Raleway-Medium.ttf
      - asset: assets/fonts/Raleway-Regular.ttf
