name: build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        device:
          - "windows"
      fail-fast: false
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v1.5.3
        with:
          channel: "stable"

      - name: Get pub dependencies
        working-directory: src/papilio_note
        run: flutter pub get

      - name: Dart analyze
        working-directory: src/papilio_note
        run: dart analyze --no-fatal-warnings

      - name: Flutter test
        working-directory: src/papilio_note
        run: flutter test --coverage

      - name: Minimum Test Coverage
        uses: VeryGoodOpenSource/very_good_coverage@v1.2.0
        with:
          path: "src/papilio_note/coverage/lcov.info"
          min_coverage: 100
